name = "Gay"
uuid = "f3dee6b2-1ce2-4cc9-bfb1-25e98f6f315b"
version = "0.1.0"

[deps]
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LispSyntax = "51c06dcf-91d3-5c9e-a52e-02df4e7cbcf5"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReplMaker = "b873ce64-0db9-51f5-a568-4457d8e49576"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
SplittableRandoms = "8efc31e9-3fb0-4277-b18c-5a3d5d07abad"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"

[extensions]
GayMetalExt = "Metal"

[compat]
AMDGPU = "1"
CUDA = "5"
Chairmarks = "1"
ColorTypes = "0.11, 0.12"
Colors = "0.12"
Dates = "1"
JSON3 = "1"
KernelAbstractions = "0.9"
LispSyntax = "0.2"
Metal = "1"
OhMyThreads = "0.7"
ParserCombinator = "≥ 2.0.0"
Pigeons = "0.4"
Printf = "1"
REPL = "1"
Random = "1"
ReplMaker = "0.2"
SplittableRandoms = "0.1"
StructTypes = "1"
julia = "≥ 1.6.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "Chairmarks"]
