[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Gay = "f3dee6b2-1ce2-4cc9-bfb1-25e98f6f315b"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
SplittableRandoms = "8efc31e9-3fb0-4277-b18c-5a3d5d07abad"

[sources.Gay]
path = ".."
